spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
          defaultZkPort: 2181
          autoAddPartitions: true
      bindings:
        inTest:
          consumer:
            autoRebalanceEnabled: true
            headerMode: raw
        outTest:
          producer:
            partitionCount: 3
